name: CFBanner
main: thesbros.bukkit.CFBanner.CFBanner
description: Bans various hacks from multiplayer servers
author: opspwns, CainFoool
version: 3.3.4
permissions:
    cfbanner.*:
        description: Gives access to all cheats/hacks
        children:
            cfbanner.fly: true
            cfbanner.xray: true
            cfbanner.minimap: true
            cfbanner.cjb: true
    cfbanner.fly:
        description: Allows zombe's fly mod for a user
        default: op
    cfbanner.xray:
        description: Allows zombe's x-ray for a user
        default: op
    cfbanner.cjb:
        description: Allows CJB's features for a user
        default: op
    cfbanner.minimap:
        description: Allows Rei's minimap cave mapping and entity radar features for a user
        default: op